export * as trendings from './rest/trendings.js'
export * as readme from './rest/readme.js'
export * as user from './rest/user.js'
export * as issue from './rest/issue.js'
export * as starred from './rest/starred.js'
